name: rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc
  - multiqc
  - salmon
  - pigz
  - r-base
  - r-tximport
  - r-deseq2
  - r-tidyverse
  - r-ggplot2
  - r-ggrepel
  - r-pheatmap
  - r-readr
